version: '3.8'

services:
  # 1. Base de Datos Relacional (PostgreSQL) - Req #11
  postgres:
    image: postgres:15-alpine
    container_name: dental_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: dental_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Base de Datos NoSQL (MongoDB) - Req #11
  mongo:
    image: mongo:6.0
    container_name: dental_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo_data:/data/db

  # 3. Cach√© (Redis) - Req #11
  redis:
    image: redis:7-alpine
    container_name: dental_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass adminpassword
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: