version: '3.8'

services:
  # 1. Base de Datos SQL (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: dental_postgres
    ports:
      - "5433:5432" # Puerto 5433 para no chocar con tu PC
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: dental_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Base de Datos NoSQL (MongoDB)
  mongo:
    image: mongo:6.0
    container_name: dental_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo_data:/data/db

  # 3. Caché (Redis)
  redis:
    image: redis:7-alpine
    container_name: dental_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass adminpassword
    volumes:
      - redis_data:/data

  # 4. Message Broker (RabbitMQ) - Req #15 y #16
  rabbitmq:
    image: rabbitmq:3-management
    container_name: dental_rabbitmq
    ports:
      - "5672:5672"   # Comunicación interna
      - "15672:15672" # Panel Web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

# SECCIÓN DE VOLUMENES 
volumes:
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data: